services:
  - type: web
    name: hoarder-web
    env: docker
    image: ghcr.io/hoarder-app/hoarder:${HOARDER_VERSION:-release}
    envVars:
      - key: MEILI_ADDR
        value: "http://meilisearch:7700"
      - key: BROWSER_WEB_URL
        value: "http://chrome:9222"
      - key: DATA_DIR
        value: "/data"   # DON'T CHANGE THIS
      # (Include any additional environment variables from your .env file here)
    disk:
      name: data
      mountPath: /data
    ports:
      - port: 3000
        containerPort: 3000

  - type: worker
    name: chrome
    internal: true
    env: docker
    image: gcr.io/zenika-hub/alpine-chrome:123
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars

  - type: worker
    name: meilisearch
    internal: true
    env: docker
    image: getmeili/meilisearch:v1.11.1
    envVars:
      - key: MEILI_NO_ANALYTICS
        value: "true"
    disk:
      name: meilisearch
      mountPath: /meili_data
